# POSTTEST7 - Tensorflow

><p> Nama : Tito Darmawan <br> NIM : 2109106042 <br> Dataset : </p>

## Import

In [2]:
import tensorflow as tf

## Pembuatan Tensorflow Random

In [3]:
random_tensor = tf.random.normal([5,5], dtype=tf.float32)

## Pembuatan Tensor dari List bilangan prima

In [4]:
list_ = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101]
prime_tensor = tf.convert_to_tensor(list_, dtype=tf.float32)
prime_tensor = tf.reshape(prime_tensor, [5, 5])

## Dimensi Kedua Tensorflow di atas

In [5]:
print("Random : ")
random_tensor.get_shape

Random : 


<bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.2903652 , -0.4766557 , -0.13242021,  1.7611532 ,  0.54819685],
       [ 0.790303  ,  0.00342993, -1.122631  ,  1.4143972 , -0.5654473 ],
       [ 1.3196427 , -1.6820697 , -0.5403496 ,  1.0782737 ,  1.0625372 ],
       [ 0.93798256, -1.9280267 , -0.69105184,  0.9910845 , -0.95426226],
       [-1.6997303 ,  1.1535716 ,  0.36433014,  0.8607499 , -0.82094795]],
      dtype=float32)>>

In [6]:
print("Prime : ")
prime_tensor.get_shape

Prime : 


<bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>>

## 5 Operasi Aritmatika Tensorflow
### 1. Tambah

In [7]:
Add = random_tensor + prime_tensor
print("Hasil Penambahan tensor random dan prime :")
print(Add)

Hasil Penambahan tensor random dan prime :
tf.Tensor(
[[  1.7096348   2.5233443   4.86758     8.761153   11.548197 ]
 [ 13.790303   17.00343    17.877369   24.414398   28.434553 ]
 [ 32.31964    35.317932   40.459652   44.078274   48.06254  ]
 [ 53.93798    57.07197    60.30895    71.99108    72.04574  ]
 [ 77.30027    84.15357    89.36433    97.86075   100.179054 ]], shape=(5, 5), dtype=float32)


### 2. Kurang

In [8]:
Subtract = random_tensor - prime_tensor
print("Hasil Pengurangan tensor random dan prime :")
print(Subtract)

Hasil Pengurangan tensor random dan prime :
tf.Tensor(
[[  -2.2903652   -3.4766557   -5.13242     -5.238847   -10.451803 ]
 [ -12.209697   -16.99657    -20.122631   -21.585602   -29.565447 ]
 [ -29.680357   -38.682068   -41.540348   -41.921726   -45.93746  ]
 [ -52.06202    -60.92803    -61.69105    -70.00892    -73.95426  ]
 [ -80.69973    -81.84643    -88.63567    -96.13925   -101.820946 ]], shape=(5, 5), dtype=float32)


### 3. Kali

In [9]:
Multiply = random_tensor * prime_tensor
print("Hasil Pengalian tensor random dan prime :")
print(Multiply)

Hasil Pengalian tensor random dan prime :
tf.Tensor(
[[-5.8073038e-01 -1.4299670e+00 -6.6210103e-01  1.2328073e+01
   6.0301652e+00]
 [ 1.0273939e+01  5.8308728e-02 -2.1329988e+01  3.2531136e+01
  -1.6397970e+01]
 [ 4.0908924e+01 -6.2236576e+01 -2.2154333e+01  4.6365768e+01
   4.9939247e+01]
 [ 4.9713074e+01 -1.1375357e+02 -4.2154163e+01  7.0367004e+01
  -6.9661148e+01]
 [-1.3427869e+02  9.5746445e+01  3.2425385e+01  8.3492737e+01
  -8.2915741e+01]], shape=(5, 5), dtype=float32)


### 4. Bagi

In [10]:
Divide = random_tensor / prime_tensor
print("Hasil Pengalian tensor random dan prime :")
print(Divide)

Hasil Pengalian tensor random dan prime :
tf.Tensor(
[[-1.4518259e-01 -1.5888523e-01 -2.6484042e-02  2.5159332e-01
   4.9836077e-02]
 [ 6.0792539e-02  2.0176030e-04 -5.9085838e-02  6.1495531e-02
  -1.9498182e-02]
 [ 4.2569119e-02 -4.5461342e-02 -1.3179258e-02  2.5076132e-02
   2.2607174e-02]
 [ 1.7697785e-02 -3.2678418e-02 -1.1328719e-02  1.3958937e-02
  -1.3072086e-02]
 [-2.1515572e-02  1.3898453e-02  4.0935972e-03  8.8737104e-03
  -8.1281979e-03]], shape=(5, 5), dtype=float32)


### 5. Pangkat

In [11]:
Divide = random_tensor ** prime_tensor
print("Hasil elemen tensor random pangkat elemen tensor prime :")
print(Divide)

Hasil elemen tensor random pangkat elemen tensor prime :
tf.Tensor(
[[ 8.43119398e-02 -1.08296484e-01 -4.07165899e-05  5.25508804e+01
   1.34369871e-03]
 [ 4.69155870e-02  0.00000000e+00 -9.00540447e+00  2.90497363e+03
  -6.59737651e-08]
 [ 5.42184082e+03 -2.27105248e+08 -1.09564103e-11  2.55474014e+01
   1.73051205e+01]
 [ 3.35986987e-02 -6.63237783e+16 -1.62236405e-10  5.29491603e-01
  -3.27903107e-02]
 [-1.58496924e+18  1.41155656e+05  0.00000000e+00  4.82022358e-07
  -2.21757146e-09]], shape=(5, 5), dtype=float32)


## Nilai Max dan Min dari Tensor Random

In [18]:
print("Max :")
tf.math.reduce_max(random_tensor).numpy()

Max :


1.7611532

In [20]:
print("Min :")
tf.math.reduce_min(random_tensor).numpy()

Min :


-1.9280267

## Penggabungan variable random_tensor dengan prime_tensor

In [23]:
print("Concat Axis 0 :")
tf.concat([random_tensor, prime_tensor], axis=0)

Concat Axis 0 :


<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-2.9036519e-01, -4.7665569e-01, -1.3242021e-01,  1.7611532e+00,
         5.4819685e-01],
       [ 7.9030299e-01,  3.4299251e-03, -1.1226310e+00,  1.4143972e+00,
        -5.6544727e-01],
       [ 1.3196427e+00, -1.6820697e+00, -5.4034960e-01,  1.0782737e+00,
         1.0625372e+00],
       [ 9.3798256e-01, -1.9280267e+00, -6.9105184e-01,  9.9108452e-01,
        -9.5426226e-01],
       [-1.6997303e+00,  1.1535716e+00,  3.6433014e-01,  8.6074990e-01,
        -8.2094795e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
      

In [25]:
print("Concat Axis 1 :")
tf.concat([random_tensor, prime_tensor], axis=1)

Concat Axis 1 :


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-2.9036519e-01, -4.7665569e-01, -1.3242021e-01,  1.7611532e+00,
         5.4819685e-01,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 7.9030299e-01,  3.4299251e-03, -1.1226310e+00,  1.4143972e+00,
        -5.6544727e-01,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 1.3196427e+00, -1.6820697e+00, -5.4034960e-01,  1.0782737e+00,
         1.0625372e+00,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [ 9.3798256e-01, -1.9280267e+00, -6.9105184e-01,  9.9108452e-01,
        -9.5426226e-01,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-1.6997303e+00,  1.1535716e+00,  3.6433014e-01,  8.6074990e-01,
        -8.2094795e-01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0100000e+02]], dtype=float32)>

## Sorting 2 Variabel diatas secara descending

In [30]:
print("random_tensor sort desc :")
tf.sort(random_tensor, direction="DESCENDING")

random_tensor sort desc :


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.7611532 ,  0.54819685, -0.13242021, -0.2903652 , -0.4766557 ],
       [ 1.4143972 ,  0.790303  ,  0.00342993, -0.5654473 , -1.122631  ],
       [ 1.3196427 ,  1.0782737 ,  1.0625372 , -0.5403496 , -1.6820697 ],
       [ 0.9910845 ,  0.93798256, -0.69105184, -0.95426226, -1.9280267 ],
       [ 1.1535716 ,  0.8607499 ,  0.36433014, -0.82094795, -1.6997303 ]],
      dtype=float32)>

In [29]:
print("prime_tensor sort desc :")
tf.sort(prime_tensor, direction="DESCENDING")

prime_tensor sort desc :


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)>